### ISSUE TITLE
[Security] Workflow reviewdog.yml is using vulnerable action reviewdog/action-stylelint

### ISSUE THREAD

**Issue by Ale0x78** [aktnk/covid19_test#5]
The workflow reviewdog.yml is referencing action reviewdog/action-stylelint using references v1. However this reference is missing the commit [77f32d929e35417e682ecc021bd1ee56d4bbef7e](https://github.com/reviewdog/action-stylelint/commits/77f32d929e35417e682ecc021bd1ee56d4bbef7e) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by aktnk** [comment]
Thank you @Ale0x78 !

Now I deleted the permission to execute GitHub actions of this repository.
And after a while, this repository will be deleted.
